# Generated by Django 2.0.2 on 2021-01-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='caption',
            field=models.CharField(max_length=140),
        ),
    ]
