# Generated by Django 2.0.2 on 2021-01-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20210115_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='test test', max_length=250),
            preserve_default=False,
        ),
    ]
