# Generated by Django 2.2.1 on 2019-07-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20190705_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
