# Generated by Django 2.2.1 on 2019-07-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20190705_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(blank=True, default='5.99'),
        ),
    ]
