# Generated by Django 2.2.1 on 2019-07-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_auto_20190705_0315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
