# Generated by Django 2.0.2 on 2021-01-15 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_auto_20190705_0340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='restaurant_owner',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='caption',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='url',
        ),
    ]
